/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_rowak_nanotunes_NativeAudioUtil */

#ifndef _Included_io_github_rowak_nanotunes_NativeAudioUtil
#define _Included_io_github_rowak_nanotunes_NativeAudioUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_rowak_nanotunes_NativeAudioUtil
 * Method:    open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_github_rowak_nanotunes_NativeAudioUtil_open
  (JNIEnv *, jclass);

/*
 * Class:     io_github_rowak_nanotunes_NativeAudioUtil
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_rowak_nanotunes_NativeAudioUtil_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_rowak_nanotunes_NativeAudioUtil
 * Method:    getMaxAmplitude
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_github_rowak_nanotunes_NativeAudioUtil_getMaxAmplitude
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
